---
- hosts: nodes
  become: true
  vars_files:
    - vagrant.yml

  tasks:

    - name: clean up the home folder
      file:
        path: /home/vagrant/{{ item }}
        state: absent
      with_items:
        - base.sh
        - chef.sh
        - cleanup.sh
        - cleanup-virtualbox.sh
        - puppetlabs-release-wheezy.deb
        - puppet.sh
        - ruby.sh
        - vagrant.sh
        - virtualbox.sh
        - zerodisk.sh

    - name: installing dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - tmux
          - python3-pip
        state: present
        update_cache: true

    - name: fetching docker repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: fetching kubernetes repo key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: adding package repos
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - deb https://download.docker.com/linux/ubuntu xenial stable
        - deb https://apt.kubernetes.io/ kubernetes-xenial main

    - name: installing docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: installing kubeadm related packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true

    - name: start docker service
      service:
        name: docker
        state: started

    - name: adding user vagrant to group docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: performing pip autoupgrade
      pip:
        name: pip
        state: latest

    - name: installing virtualenv
      pip:
        name: virtualenv
        state: latest

    - name: Install Docker Compose via PIP
      pip: name=docker-compose

    - name: building the /etc/hosts file with all nodes
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.private_ip }} {{ item.hostname }}"
        regexp: "^{{ item.private_ip }} {{ item.hostname }}$"
        state: present
      with_items: "{{ instances }}"

    - name: copying the ssh key to the nodes
      copy:
        src: private-key
        dest: /home/vagrant/private-key
        mode: 0600
        group: root
        owner: vagrant

    - name: copying ssh configuration
      copy:
        src: ssh-config
        dest: /home/vagrant/.ssh/config
        mode: 0600
        group: root
        owner: vagrant

    - name: fixing the hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: adjusting the /etc/hosts to the new hostname
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - regexp: '^127\.0\.0\.1'
          line: "127.0.0.1 localhost {{ inventory_hostname }}"
        - regexp: '^127\.0\.1\.1'
          line: "127.0.1.1 {{ inventory_hostname }}"


